### ISSUE TITLE
[feat] `react-x/no-unknown-property` for MDX and other non-TS envs

### ISSUE THREAD

**Issue by karlhorky** [Rel1cx/eslint-react#846]
### Describe the problem

Similar to https://github.com/Rel1cx/eslint-react/issues/834

I ran into an issue today that `react-x/no-unknown-property` is not implemented in `eslint-plugin-react-x`, as noted in https://github.com/Rel1cx/eslint-react/issues/85#:~:text=members%C2%A0%23234-,The%20following%20can%20be%20enforced%20by%20TypeScript%2C%20no%20need%20to%20implement%20them,-react/jsx%2Dno:

> ### The following can be enforced by TypeScript, no need to implement them

> * `react/no-unknown-property`

This causes problems for environments where TypeScript is not available

Eg. [there is not yet full TypeScript support for MDX files](https://github.com/mdx-js/mdx-analyzer/issues/292), and [it appears ESLint doesn't support multiple parsers for a set of files](https://github.com/eslint/eslint/issues/17655) (eg. for trying to use `typescript-eslint` parser along with the MDX parser).

### Describe the solution you'd like

It would be great to get `react-x/no-unknown-property` implemented for other languages like MDX? (and also just for completeness, for other situations where TypeScript cannot be used)

### Alternatives considered

Keep using `react/no-unknown-property` via `eslint-plugin-react`

### Additional context

Ideally, this rule would be implemented also with abilities to extend for other environments like React Three Fiber (a missing feature of `react/no-unknown-property`):

- https://github.com/jsx-eslint/eslint-plugin-react/issues/3423

**Comment by Rel1cx** [comment]
I will add this rule, but as you mentioned, the issue of applicability across different environments, rather than adding options to rules, I think a better approach is to provide `react-dom/no-unknown-property`, similar to `react/no-unknown-property`, which is essentially a `react-dom` rule. Other environments (not necessarily provided by us) would offer corresponding `react-native/no-unknown-property`, `react-three-fiber/no-unknown-property`, etc.

This way, not only can the `no-unknown-property` rule in each environment be updated and released according to its own versioning cadence (to sync the propertires changes), but it also reduces the complexity of JS tool configurations, especially with `ESLint`, where we've heard too many complaints about overly complex configurations. This is one of the main reasons many users have switched from `ESLint` to `biome`, `oxlint` recently.

We believe that through better rule design and plugin positioning, we can avoid configuration complexity without sacrificing functionality.

**Comment by karlhorky** [comment]
@rEl1cx thanks, confirmed that `react-dom/no-unknown-property` works 🎉 (also with MDX files)
